### ISSUE TITLE
More white space and some buttons

### ISSUE THREAD

**Issue by Nowena** [gomgon/UserCSS#6]
I found more white spaces and there are some buttons that are white

![Opera Snapshot_2019-07-15_121110_www last fm](https://user-images.githubusercontent.com/52898460/61235874-2db02a00-a6fc-11e9-9538-c94bc9bab43b.png)
![Opera Snapshot_2019-07-15_121208_www last fm](https://user-images.githubusercontent.com/52898460/61235875-2e48c080-a6fc-11e9-99aa-c78ea2af3cb6.png)
![Opera Snapshot_2019-07-15_121445_www last fm](https://user-images.githubusercontent.com/52898460/61235876-2e48c080-a6fc-11e9-8ef8-9aac9f1cc5cc.png)
![Opera Snapshot_2019-07-15_121545_www last fm](https://user-images.githubusercontent.com/52898460/61235877-2e48c080-a6fc-11e9-93a2-2a6126db1fd5.png)
![Opera Snapshot_2019-07-15_121744_www last fm](https://user-images.githubusercontent.com/52898460/61235878-2e48c080-a6fc-11e9-9d2b-bbf9b34cf371.png)
![Opera Snapshot_2019-07-15_122039_www last fm](https://user-images.githubusercontent.com/52898460/61235879-2e48c080-a6fc-11e9-91fe-54cc0e960cc2.png)
![Opera Snapshot_2019-07-15_122148_www last fm](https://user-images.githubusercontent.com/52898460/61235881-2ee15700-a6fc-11e9-984e-d37f49f6b2e2.png)
![Opera Snapshot_2019-07-15_122225_www last fm](https://user-images.githubusercontent.com/52898460/61235882-2ee15700-a6fc-11e9-9aee-9cd725fe86bc.png)

**Comment by Nowena** [comment]
here are more

![Opera Snapshot_2019-07-15_175717_www last fm](https://user-images.githubusercontent.com/52898460/61254527-636c0780-a72a-11e9-864c-ab590d330e60.png)
![Opera Snapshot_2019-07-15_175745_www last fm](https://user-images.githubusercontent.com/52898460/61254529-64049e00-a72a-11e9-8010-cc04c29807ca.png)
![Opera Snapshot_2019-07-15_175914_www last fm](https://user-images.githubusercontent.com/52898460/61254531-64049e00-a72a-11e9-9c1f-f3dd982e6200.png)

**Comment by Nowena** [comment]
no word on this?

**Comment by gomgon** [comment]
Sorry I have been pretty busy.

So, about the buttons in the header;
The issue is that with the new design making the left half of the header a gradient of the image main color, black and white pictures therefore makes a grey gradient.

By styling those buttons like others "secondary buttons", it ends up looking like this:
![header](https://user-images.githubusercontent.com/32310149/62475325-1b7a5680-b7a5-11e9-8139-dc006e62adb9.png)

I hate borders and box-shadow, but I might have to use that to make them more visible.
Or just use a fixed color but less bright, I'll see.


As for the icons missing artist/album/avatar picture, unfortunately there is nothing in the code differentiating them from icons not missing a picture (same class, and it doesn't use a sprite either), so I cant modify those specifically.
It's a bit of an eyesore I agree, personally I upload a picture whenever something I listen doesn't have one.

Regardless, I'll fix the header and "Listeners you know" buttons today.

**Comment by Nowena** [comment]
hey thanks again for your work. those borders on the buttons dont look all that bad, I actually like how the buttons change according to the gradient of the picture. and too bad you cannot do anything about the missing pics, I also upload all the pics I can, dislike how it looks like but oh well

**Comment by gomgon** [comment]
Finally found a way to make the items missing a picture less bright.

**Comment by Nowena** [comment]
Thanks, you are the best.
